declare module '*.css';
declare module '*.less';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.webp'
declare module '*.svg'
declare module '*/config/*'
declare module '@config/router.js'
declare module '*/config/router.js'